import type { Metadata } from "next";
import { Arima, Roboto } from "next/font/google";
import "@/styles/globals.css";
import Sidebar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";
import Providers from "@/lib/context/provider";

const arima = Arima({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-arima",
});
const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* const User = null; */
const User = { id: "1", name: "John Doe", role: "admin" };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arima.variable} ${roboto.variable} antialiased`}>
        <Providers>
          {User ? (
            <div className="flex ">
              <Sidebar />
              <div className="min-h-screen w-screen">
                <Header />
                <main className="bg-background h-full py-6 lg:py-14 pr-6 pl-6 lg:pr-14 lg:pl-86 3xl:pl-99">
                  {children}
                </main>
              </div>
            </div>
          ) : (
            <main className="w-screen h-screen overflow-hidden">
              {children}
            </main>
          )}
        </Providers>
      </body>
    </html>
  );
}
