import type { Metadata } from "next";
import { Arima, Roboto } from "next/font/google";
import "@/styles/globals.css";
import Sidebar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";
import Providers from "@/lib/context/provider";

const arima = Arima({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-arima",
});
const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arima.variable} ${roboto.variable} antialiased`}>
        <Providers>
          <div className="flex h-screen">
            <Sidebar />
            <div className="flex-1 flex flex-col h-full ">
              <Header />
              <main className="lg:flex-1 w-screen bg-background py-6 lg:py-10 pr-6 pl-6 lg:pr-14 lg:pl-86 overflow-hidden">
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
