import type { Metadata } from "next";
import { Arima, Roboto } from "next/font/google";
import "@/styles/globals.css";
import Sidebar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";
import Providers from "@/lib/context/provider";

const arima = Arima({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-arima",
});
const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const User = null;
/* const User = {id: "1", name: "John Doe", role: "admin"} */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arima.variable} ${roboto.variable} antialiased`}>
        <Providers>
          {User ? (
            <div className="flex h-screen w-screen">
              <Sidebar />
              <div className="w-full h-full">
                <Header />
                <main className=" w-full h-full bg-background  border py-6 lg:py-10 pr-6 pl-6 lg:pr-10 lg:pl-82 overflow-auto ">
                  {children}
                </main>
              </div>
            </div>
          ) : (
            <main className="w-screen h-screen overflow-hidden">
              {children}
            </main>
          )}
        </Providers>
      </body>
    </html>
  );
}
